[relaychain]
chain = "rococo-local"
default_command = "./bin-1.17.4/polkadot"

[[relaychain.nodes]]
name = "alice"
validator = true
ws_port = 9900

[[relaychain.nodes]]
name = "bob"
validator = true
ws_port = 9901

[[parachains]]
id = 2000
addToGenesis = true
cumulus_based = true
chain = "dev"

[[parachains.collators]]
name = "collator01"
command = "./target/release/xcavate-parachain-node"
ws_port = 9910
rpc_port = 8833
args = ["-lxcm=trace,pallet-assets=trace"]

[[parachains.collators]]
name = "collator02"
ws_port = 9911
rpc_port = 8822
command = "./target/release/xcavate-parachain-node"
args = ["-lxcm=trace,pallet-assets=trace"]